from django.db import connection

sql_commands = [
    'CREATE TABLE "portfolio_transaction" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(4) NOT NULL, "quantity" numeric(18, 4) NOT NULL, "price" numeric(18, 4) NOT NULL, "time" timestamptz NOT NULL, "portfolio_id" bigint NOT NULL, "symbol_id" bigint NOT NULL);',
    'ALTER TABLE "portfolio_transaction" ADD CONSTRAINT "portfolio_transaction_portfolio_id_9a795480_fk_portfolio" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio_portfolio" ("id") DEFERRABLE INITIALLY DEFERRED;',
    'ALTER TABLE "portfolio_transaction" ADD CONSTRAINT "portfolio_transaction_symbol_id_7c466a13_fk_stocks_st" FOREIGN KEY ("symbol_id") REFERENCES "stocks_stockmaster" ("id") DEFERRABLE INITIALLY DEFERRED;',
    'CREATE INDEX "portfolio_transaction_portfolio_id_9a795480" ON "portfolio_transaction" ("portfolio_id");',
    'CREATE INDEX "portfolio_transaction_symbol_id_7c466a13" ON "portfolio_transaction" ("symbol_id");'
]

with connection.cursor() as cursor:
    for sql in sql_commands:
        try:
            print(f"Executing: {sql[:50]}...")
            cursor.execute(sql)
        except Exception as e:
            print(f"Error: {e}")
