# Generated by Django 6.0.3 on 2026-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('market', models.CharField(db_index=True, max_length=2)),
                ('market_price', models.FloatField(default=0.0)),
                ('day_change', models.FloatField(default=0.0)),
                ('day_change_pct', models.FloatField(default=0.0)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('data_source', models.CharField(default='unknown', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
