# Generated by Django 5.1.6 on 2026-03-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_missing_portfolio_fields'),
        ('portfolio', '0003_create_holding_table'),
    ]

    operations = [
    ]
