<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-24 09:29
=======
# Generated by Django 5.1.6 on 2026-03-21 15:42
>>>>>>> f676874015cfdcfa865c247090c40e9cf22a2aba

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='StockMaster',
=======
            name='Stock',
>>>>>>> f676874015cfdcfa865c247090c40e9cf22a2aba
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('market', models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('OTHER', 'Other')], default='NSE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stockmaster')),
            ],
            options={
                'ordering': ['-updated_at'],
=======
                ('sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('stock', 'timestamp')},
>>>>>>> f676874015cfdcfa865c247090c40e9cf22a2aba
            },
        ),
    ]
