# Generated by Django 6.0.3 on 2026-03-25 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='open',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('stock', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='updated_at',
        ),
    ]
