# Generated by Django 6.0.3 on 2026-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaster',
            name='high_52week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmaster',
            name='low_52week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmaster',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
