# Generated by Django 5.1.6 on 2026-03-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_link_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_link_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
