# Generated by Django 5.1.6 on 2026-03-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mlops", "0001_initial"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcluster",
            name="portfolio",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="clusters", to="portfolio.portfolio"),
        ),
        migrations.AlterUniqueTogether(
            name="stockcluster",
            unique_together={("portfolio", "stock")},
        ),
    ]
